import type { Metadata } from "next";
import "@/app/globals.css";
import Provider from "@/context/Provider";

export const metadata: Metadata = {
  title: "Messenger clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }: any) {
  return (
    <html lang="en">
      <Provider session={session}>
        <body>{children}</body>
      </Provider>
    </html>
  );
}
